#ifndef BOOST_CONTEXT_BOOST_DEPENDENCIES_CONFIG_HPP
#define BOOST_CONTEXT_BOOST_DEPENDENCIES_CONFIG_HPP

#if defined(_WIN32) && !defined(BOOST_WINDOWS)
#define BOOST_WINDOWS
#endif

#endif // BOOST_CONTEXT_BOOST_DEPENDENCIES_CONFIG_HPP
